### PR TITLE
Add Bomb, Arrow and Map Select Cheats

### PR DESCRIPTION
**Pull request by hallcristobal**

### CODE REVIEW

**Comment by CryZe** [comment]
I don't know if I agree with Reload Area and Map Select. You can already do both of these via the Warp Menu. Also this needs to be rebased.

**Comment by CryZe** [comment]
I think I'll close this and selectively copy paste stuff from this into my code. That's probably easier for both you and me :P

**Comment by hallcristobal** [comment]
That's fair, I personally find Map Select easier, probably just because I've used it so much already.

**Comment by CryZe** [comment]
Yeah, I guess. If you have any specific improvement suggestions to improve the Warp Menu, I'd like to know.

**Pull request closed without merging**
